changelog:
  exclude:
    labels:
      - automated-reposync-pr
      - autoupdate
      - back-end
      - release
      - hidden
    authors:
      - bot-docsteam
  categories:
    - title: New Features
      labels:
        - new-feature
    - title: New Integration Docs
      labels:
        - new-integration
    - title: Improvements
      labels:
        - content-update
    - title: Fixes
      labels:
        - fixed-content
        - fixed-site
    - title: Other Updates
      labels:
        - "*"
