
steps:
  - label: ":hammer: Build Dependencies"
    command:
      - pwd
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - yarn install --frozen-lockfile
      - bundle install
      - chown -R jekyll /workdir
      # - make intialize-work-dir
      - make build
    env:
      SEGMENT_CONTEXTS: "snyk,npm"
    plugins:
      - docker#v3.3.0:
          image: jekyll/jekyll
          environment:
            - NPM_TOKEN
            - AWS_REGION
            - AWS_DEFAULT_REGION
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_SESSION_TOKEN
            - BUILDKITE_BRANCH
  
