steps:
  - label: ":hammer: Build Dependencies and Docs"
    command:
      - make test
      - make build
      - make zip-artifacts
    env:
      SEGMENT_CONTEXTS: "snyk, aws-credentials"
    artifact_paths:
        - build_package.tar.gz
    plugins:
      - docker#v3.3.0:
          image: jekyll/jekyll
          environment:
            - BUILDKITE_BRANCH

      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v3.0.0:
          key: "v1-cache-gem-{{ checksum 'Gemfile.lock' }}"
          paths: [ "vendor/" ]
          save: true
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v3.0.0:
          key: "v1-cache-npm-{{ checksum 'yarn.lock' }}"
          paths: [ "node_modules/" ]
          save: true
     
  - wait

  - label: ":shipit: Deploy Docs to S3"
    env:
      SEGMENT_CONTEXTS: "aws-credentials"
    branches: master staging
    command:
      - buildkite-agent artifact download build_package.tar.gz .
      - make unzip-artifacts
      - make upload-docs
