steps:
  - label: ":hammer: Build Dependencies"
    command:
      - make build
    env:
      SEGMENT_CONTEXTS: "snyk, aws-credentials"
    plugins:
      - docker#v3.3.0:
          image: jekyll/jekyll
          environment:
            - BUILDKITE_BRANCH
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v1.0.0:
          key: "v1-cache-gem-{{ checksum 'Gemfile.lock' }}"
          paths: [ "vendor/" ]
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v1.0.0:
          key: "v1-cache-npm-{{ checksum 'yarn.lock' }}"
          paths: [ "node_modules/" ]
     
  - wait

  - label: ":shipit: Deploy to S3"
    command:
      - make upload-assets 
    env:
      SEGMENT_CONTEXTS: "snyk, aws-credentials"
    branches: master staging
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v1.0.0:
          key: "v1-cache-npm-{{ checksum 'yarn.lock' }}"
          paths: [ "node_modules/" ]
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v1.0.0:
          key: "v1-cache-gem-{{ checksum 'Gemfile.lock' }}"
          paths: [ "vendor/" ]
