steps:
  - label: ":hammer: Build Dependencies"
    command:
      # - make build
      - yarn install
      # - bundle install
    env:
      SEGMENT_CONTEXTS: "snyk"
    plugins:
      - docker#v3.3.0:
          image: jekyll/jekyll
          environment:
            - BUILDKITE_BRANCH
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v1.0.0:
          key: "v1-npm-cache-{{ checksum 'yarn.lock' }}"
          paths: [ "node_modules/" ]
          s3_bucket_name: S3_BUCKET_NAME
      # - ssh://git@github.com/segmentio/cache-buildkite-plugin#v1.0.0:
      #     key: "v1-gem-cache-{{ checksum 'Gemfile.lock' }}"
      #     paths: [ "vendor/" ]
      #     s3_bucket_name: "${S3_BUCKET_NAME}"
