steps:
  - label: ":hammer: Build Dependencies"
    command:
      # - make build
      # - mkdir test && touch test/test.txt
      - yarn install
      - bundle install
    env:
      SEGMENT_CONTEXTS: "snyk, aws-credentials"
    plugins:
      - docker#v3.3.0:
          image: jekyll/jekyll
          environment:
            - BUILDKITE_BRANCH
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v1.0.0:
          key: "v1-cache-{{ checksum 'yarn.lock' }}--{{ checksum 'Gemfile.lock' }}"
          paths: [ "node_modules/", "vendor/" ]