#!/bin/bash

set -euo pipefail

source "${SEGMENT_LIB_PATH}/aws.bash"

BRANCH="${BUILDKITE_BRANCH}"
echo "--- Branch ${BRANCH}"

# Use appropriate role to sync to S#



# Assign S3 Bucket and use the appropriate role to authenticate to S3
S3_BUCKET_NAME="segment-docs-stage"
role_arn="arn:aws:iam::355207333203:role/buildkite-agent"

if [ ${BRANCH} = 'master' ]
then
  S3_BUCKET_NAME="segment-docs-prod"
  role_arn="arn:aws:iam::752180062774:role/buildkite-agent"
fi
assume-role "${role_arn}"

# Only Sync to S3 on Build step and for prod/staging environments
if [[ ${BUILDKITE_LABEL} = ':hammer: Build Dependencies' ]] && [[ ${BRANCH} = 'master' || ${BRANCH} = 'staging' ]]; 
then
  echo "--- Uploading to s3://${S3_BUCKET_NAME}/docs"
  aws s3 sync _site/ s3://${S3_BUCKET_NAME}/docs/
fi

export S3_BUCKET_NAME
echo "--- Build Complete"
# vim: ft=sh
