#!/bin/bash

set -euo pipefail

source "${SEGMENT_LIB_PATH}/aws.bash"

BRANCH="${BUILDKITE_BRANCH}"
echo "--- Branch ${BRANCH}"

# Use appropriate role to sync to S#
# Assign S3 Bucket and use the appropriate role to authenticate to S3
S3_BUCKET_NAME="segment-docs-stage"
role_arn="arn:aws:iam::355207333203:role/buildkite-agent"

if [ ${BRANCH} = 'master' ]
then
  S3_BUCKET_NAME="segment-docs-prod"
  role_arn="arn:aws:iam::752180062774:role/buildkite-agent"
fi

s3-sync() {
  echo "--- Uploading to s3://${S3_BUCKET_NAME}/docs"
  ls -a
  aws s3 sync _site s3://${S3_BUCKET_NAME}/docs/ --delete
}

# Only Sync to S3 on Build step and for prod/staging environments
if [[ ${BRANCH} = 'master' || ${BRANCH} = 'staging' ]]; 
then
  run-with-role "${role_arn}" s3-sync
fi

echo "--- Build Complete"
# vim: ft=sh
