items:
- product_display_name: Personas
  slug: personas
  tiers:
    free: false
    team: false
    business: true
    add-on: true
- product_display_name: Personas Identity Graph
  slug: personas-id
  tiers:
    free: false
    team: false
    business: true
    add-on: true
- product_display_name: Personas Journey Orchestration
  slug: personas-j
  tiers:
    free: false
    team: false
    business: true
    add-on: true
- product_display_name: Protocols
  slug: protocols
  tiers:
    free: false
    team: false
    business: true
    add-on: true
- product_display_name: Access Management
  slug: iam
  tiers:
    free: false
    team: false
    business: true
    add-on: false
- product_display_name: Replay
  slug: replay
  tiers:
    free: false
    team: false
    business: true
    add-on: false
- product_display_name: Privacy Portal
  slug: privacy
  tiers:
    free: true
    team: true
    business: true
    add-on: false
- product_display_name: Warehouses
  slug: warehouses
  tiers:
    free: false
    team: false
    business: true
    add-on: true
- product_display_name: Warehouse custom sync
  slug: warehouse-sync
  tiers:
    free: false
    team: false
    business: true
    add-on: true
