items:
- product_display_name: Personas
  slug: personas
  plan-note: "Personas is available as an add-on for Business tier plans."
  tiers:
    free: false
    team: false
    business: true
    add-on: true
- product_display_name: Personas Identity Graph
  slug: personas-id
  tiers:
    free: false
    team: false
    business: true
    add-on: true
- product_display_name: Personas Journey Orchestration
  slug: personas-j
  tiers:
    free: false
    team: false
    business: true
    add-on: true
- product_display_name: Protocols
  slug: protocols
  plan-note: "Protocols is available as an add-on for Business tier plans."
  tiers:
    free: false
    team: false
    business: true
    add-on: true
- product_display_name: Access Management
  slug: iam
  plan-note: "Access Management is available for all Business tier plans."
  tiers:
    free: false
    team: false
    business: true
    add-on: false
- product_display_name: Replay
  slug: replay
  plan-note: "Replay is available to all Business tier plans."
  tiers:
    free: false
    team: false
    business: true
    add-on: false
- product_display_name: Privacy Portal
  slug: privacy
  plan-note: "The Privacy Portal is available to all Business tier plans."
  tiers:
    free: true
    team: true
    business: true
    add-on: false
- product_display_name: Warehouses
  slug: warehouses
  plan-note: "All Segment plans may have 1 warehouse. Business tier plans may have more."
  tiers:
    free: true
    team: true
    business: true
    add-on: false
- product_display_name: Warehouse custom sync
  slug: warehouse-sync
  tiers:
    free: false
    team: false
    business: true
    add-on: true
