items:
- product_display_name: Engage Foundations
  slug: engage-foundations
  plan-note: "Engage Foundations requires a Business tier account and includes Unify."
  addon: true
  plans:
    free: false
    team: false
    business: true
  # addons:
  #   unify: true
  #   engage-foundations: true
  #   engage-plus: false
- product_display_name: Engage Premier
  slug: engage-premier
  plan-note: "Engage Premier requires a Business tier account and includes Engage Foundations and Unify."
  addon: true
  plans:
    free: false
    team: false
    business: true
  # addons:
  #   unify: false
  #   engage-foundations: false
  #   engage-plus: true

- product_display_name: Unify
  slug: unify
  plan-note: "Unify requires a Business tier account and is included with Engage."
  addon: true
  plans:
    free: false
    team: false
    business: true
  # addons:
  #   unify: true
  #   engage-foundations: false
  #   engage-plus: false

- product_display_name: Protocols
  slug: protocols
  plan-note: "Protocols is available as an add-on for Business plans only."
  addon: true
  plans:
    free: false
    team: false
    business: true
- product_display_name: Advanced Access Management
  slug: iam
  plan-note: "Advanced Access Management is available for all Business plans."
  plans:
    free: false
    team: false
    business: true
    add-on: false
- product_display_name: Replay
  slug: replay
  plan-note: "Replay is available to all Business plans."
  plans:
    free: false
    team: false
    business: true
    add-on: false
- product_display_name: Privacy Portal
  slug: privacy
  plans:
    free: true
    team: true
    business: true
    add-on: false
- product_display_name: Warehouses
  slug: warehouses
  plan-note: "Free and Team plan workspaces can have 1 warehouse. Business plans can have more than one, and include custom sync schedules and filtering."
  plans:
    free: true
    team: true
    business: true
    add-on: false
- product_display_name: Warehouse custom sync
  slug: warehouse-sync
  plans:
    free: false
    team: false
    business: true
    add-on: true
- product_display_name: Data Lakes
  slug: data-lakes
  plans:
    free: false
    team: false
    business: true
    add-on: false
- product_display_name: Audit Trail
  slug: audit-trail
  plans:
    free: false
    team: false
    business: true
    add-on: false
- product_display_name: Single Sign-on
  slug: sso
  plan-note: "Single Sign-on is only available in Business plan workspaces."
  plans:
    free: false
    team: false
    business: true
    add-on: false
- product_display_name: Multi-factor authentication
  slug: mfa
  plan-note: "MFA is available to all Segment plans, but cannot be used with SSO."
  plans:
    free: true
    team: true
    business: true
    add-on: false
- product_display_name: Workspace Home page
  slug: workspace-home
  plan-note: "The Workspace Home page is currently available in Business plan workspaces, to workspace Owners only."
  plans:
    free: false
    team: false
    business: true
    add-on: false
- product_display_name: Destination Actions
  slug: dest-actions
  plan-note: "Destination Actions are available for all Segment plans. Self-service plans are limited to two conditions per Trigger."
  plans:
    free: true
    team: true
    business: true
    add-on: false
- product_display_name: Journeys
  slug: journeys
  plan-note: "Journeys is available to Personas Advanced customers"
  plans:
    free: false
    team: false
    business: true
    add-on: true
- product_display_name: Regional Segment
  slug: regional
  plan-note: "Regional Segment is available to customers on the Business Tier plan."
  plans:
    free: false
    team: false
    business: true
    add-on: false

- product_display_name: Public API
  slug: papi
  plan-note: "The Public API is available to customers on Team or Business plans."
  plans:
    free: false
    team: true
    business: true
    add-on: false
